#!/bin/sh
cp pkernel ./virtual_machine/disk

qemu-system-x86_64 -enable-kvm \
  -machine q35 \
  -cpu host \
  -smp 4 \
  -bios ./virtual_machine/uefi.bios\
  -drive file=fat:rw:./virtual_machine/disk/,format=raw,media=disk\
  -device qemu-xhci,id=xhci \
  -device usb-kbd,bus=xhci.0 \
  -drive file=./virtual_machine/nvme.img,if=none,id=nvme0 \
  -device nvme,drive=nvme0,serial=pkernel0 \
  -m 256M \
  -display gtk,show-tabs=off,show-menubar=off \
  -serial stdio
