#!/bin/sh
cp pkernel ./virtual_machine/disk

qemu-system-x86_64 -enable-kvm \
  -machine q35 \
  -bios ./virtual_machine/uefi.bios\
  -drive file=fat:rw:./virtual_machine/disk/,format=raw,media=disk\
  -device qemu-xhci,id=xhci \
  -device usb-kbd,bus=xhci.0 \
  -m 256M \
  -display gtk,show-tabs=off,show-menubar=off 
