#!/bin/sh
cp pkernel ./virtual_machine/disk

qemu-system-x86_64 -enable-kvm -bios ./virtual_machine/uefi.bios\
  -drive file=fat:rw:./virtual_machine/disk/,format=raw,media=disk\
  -device qemu-xhci,id=xhci \
  -m 256M
